CREATE SEQUENCE <<SCHEMA_NAME>>.MS_TAG_SEQ   INCREMENT 1   START 1001   MINVALUE 1   CACHE 1;
CREATE SEQUENCE <<SCHEMA_NAME>>.MS_TAG_TYPE_SEQ   INCREMENT 1   START 1001   MINVALUE 1   CACHE 1;
CREATE SEQUENCE <<SCHEMA_NAME>>.MS_TAGS_SEQ   INCREMENT 1   START 1001   MINVALUE 1   CACHE 1;

CREATE SEQUENCE <<SCHEMA_NAME>>.HIBERNATE_SEQUENCE  INCREMENT 1  MINVALUE 1 START 1  CACHE 1;
