CREATE TABLE <<AUDIT_SCHEMA>>.SD_TENANT_AUD
(
	TENANT_ID_N			NUMERIC(19,0)  ,
	NAME_V				VARCHAR(255)  ,
	START_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	END_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE    ,
	REV integer NOT NULL,
	REVTYPE				NUMERIC(19,0)
);

CREATE TABLE <<AUDIT_SCHEMA>>.SD_STATUS_AUD
(
	STATUS_N			NUMERIC(19,0)  ,
	NAME_V				VARCHAR(255),
	TENANT_ID_N			NUMERIC(19,0),
	START_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	END_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE    ,
		REV integer NOT NULL,
	REVTYPE				NUMERIC(19,0)

);


CREATE TABLE <<AUDIT_SCHEMA>>.SD_LIFECYCLE_AUD
(
	LIFECYCLE_ID_N			NUMERIC(19,0)  ,
	NAME_V				VARCHAR(255)  ,
	TENANT_ID_N			NUMERIC(19,0),
	START_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	END_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE    ,
	REV integer NOT NULL,
	REVTYPE				NUMERIC(19,0)

);

CREATE TABLE <<AUDIT_SCHEMA>>.SD_LIFECYCLE_OPERATIONS_AUD
(
	LIFECYCLE_ID_N			NUMERIC(19,0),
	OPERATION_V			VARCHAR(255)  ,
	SOURCE_STATUS_N			NUMERIC(19,0),
	ALLOW_N				NUMERIC(1,0)  ,
	REV integer NOT NULL,
	REVTYPE				NUMERIC(19,0)

);

CREATE TABLE <<AUDIT_SCHEMA>>.SD_LIFECYCLE_STATE_TRANSITION_AUD
(
	LIFECYCLE_ID_N			NUMERIC(19,0)    ,
	SOURCE_STATUS_N			NUMERIC(19,0)    ,
	TARGET_STATUS_N			NUMERIC(19,0)    ,
	ALLOW_N				NUMERIC(1,0)  ,
	REV integer NOT NULL,
	REVTYPE				NUMERIC(19,0)

);


CREATE TABLE <<AUDIT_SCHEMA>>.SD_ENTITY_TYPE_AUD
(
	ENTITY_TYPE_N			NUMERIC(19,0)  ,
	NAME_V				VARCHAR(255)   ,
	TENANT_ID_N			NUMERIC(19,0)    ,
	START_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	END_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	STATUS_N			NUMERIC(19,0)    ,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE    ,
	REV integer NOT NULL,
	REVTYPE				NUMERIC(19,0)

);

CREATE TABLE <<AUDIT_SCHEMA>>.SD_CURRENCY_AUD
(
	CURRENCY_V			VARCHAR(5)  ,
	NAME_V				VARCHAR(255)   ,
	NO_OF_DECIMALS_N		NUMERIC(2,0)    ,
	TENANT_ID_N			NUMERIC(19,0)    ,
	START_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	END_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	STATUS_N			NUMERIC(19,0)    ,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE    ,
	REV integer NOT NULL,
	REVTYPE				NUMERIC(19,0)

);


CREATE TABLE <<AUDIT_SCHEMA>>.SD_LANGUAGE_AUD
(
	LANGUAGE_ID_V			VARCHAR(20) PRIMARY KEY,
	NAME_V				VARCHAR(255)  ,
	TENANT_ID_N			NUMERIC(19,0)    ,
	START_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	END_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	STATUS_N			NUMERIC(19,0)    ,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE    ,
	REV integer NOT NULL,
	REVTYPE				NUMERIC(19,0)

);


CREATE TABLE <<AUDIT_SCHEMA>>.MS_TAG_TYPE_AUD
(
    	TAG_TYPE_ID_N			NUMERIC(19,0)  ,
   	NAME_V				VARCHAR(255)  ,
	START_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	END_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	STATUS_N			NUMERIC(19,0)    ,
	TENANT_ID_N			NUMERIC(19,0)    ,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE    ,
	REV integer NOT NULL,
	REVTYPE				NUMERIC(19,0)

);

--1	-  Market segment
--2	-  Image

CREATE TABLE <<AUDIT_SCHEMA>>.MS_TAG_AUD
(
    	TAG_MASTER_ID_N			NUMERIC(19,0)  ,
   	NAME_V				VARCHAR(255)  ,
	START_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	END_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	STATUS_N			NUMERIC(19,0)    ,
	TAG_TYPE_ID			NUMERIC(19,0)    ,
	TENANT_ID_N			NUMERIC(19,0)    ,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE    ,
	REV integer NOT NULL,
	REVTYPE				NUMERIC(19,0)

);

--1	- Indra nagar		- 1/1/2001 - 31/12/2099 -	1 - 1
--2	- Background image	- 1/1/2001 - 31/12/2099 -	1 - 2


CREATE TABLE <<AUDIT_SCHEMA>>.MS_TAGS_AUD
(
	TAG_ID_N			NUMERIC(19,0)  ,
	ENTITY_TYPE_N			NUMERIC(19,0)    ,
	ENTITY_ID_N			NUMERIC(19,0)  ,
	TAG_MASTER_ID_N			NUMERIC(19,0)    ,
	TAG_VALUE_V			VARCHAR(2000),
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE    ,
	REV integer NOT NULL,
	REVTYPE				NUMERIC(19,0)

);

CREATE TABLE <<AUDIT_SCHEMA>>.SD_ENUMERATION_TYPE_AUD
(
	ENUMERATION_TYPE_ID_N		NUMERIC(19,0)  ,
	NAME_V				VARCHAR(255)  ,
	START_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	END_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE    ,
	REV integer NOT NULL,
	REVTYPE				NUMERIC(19,0)

);

CREATE TABLE <<AUDIT_SCHEMA>>.SD_ENUMERATIONS_AUD
(
	ENUMERATION_TYPE_ID_N		NUMERIC(19,0)  ,
	ENUMERATION_ID_N		NUMERIC(19,0),
	NAME_V				VARCHAR(255)  ,
	START_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	END_DATE_DT			TIMESTAMP WITH TIME ZONE  ,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE    ,
	REV integer NOT NULL,
	REVTYPE				NUMERIC(19,0)

);
